project:
  type: website

website:
  sidebar:
    title: "R for Geospatial"
    tools: 
      - icon: twitter
        href: https://twitter.com/Centroid_CSU
      - icon: github
        href: https://github.com/ccmothes/R-for-Geospatial
    style: "docked"
    search: true
    alignment: "center"
    contents:
      - text: "Welcome"
        href: index.qmd

   
  page-footer: "Copyright 2022, Caitlin Mothes"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

