---
title: "Getting Started"
---

This is the set-up page for the **R for Geospatial** workshop. You ***must*** complete all steps on this page before the first day of the workshop. If you have any issues, we will have set-up hours during the 30 minutes before the start of Day 1, or you can email ccmothes\@colostate.edu beforehand.

## Install R and RStudio

**R** is an open source language and software environment for statistical analysis and graphics (plus so much more!). You must first download the R software (for free) here: <https://www.r-project.org/>.

*Note: If you already have R installed, we recommend that you have at least version 4.0.0. or greater. At minimum you will need R version \> 3.5.0 to use the required packages.*

**RStudio** is a (also free) R Integrated Development Environment (IDE) that provides a built-in editor and other advantages such as version control and project management. Once you have the R software installed on your computer, you can install RStudio Desktop here: [https://www.rstudio.com/products/rstudio/.](https://www.rstudio.com/products/rstudio/)

## Package Installation

While the R software comes with many pre-loaded functions (referred to as 'base R' functions), there are thousands of R packages that provide additional reusable R functions. In order to use these functions you need to first install the package to your local machine using the `install.packages()` function. Once a package is installed on your computer you don't need to install it again (but you may have to update it). Anytime you want to use the package in a new R session you can load it with the `library()` function.

The packages we are using for this workshop are listed below:

+:-------------------------------------------------------------------:+:--------------------------------------------------------:+:-------------------------------------------:+:-----------------------------------------------:+:-------------------------------------------------:+
| **Data Retrieval**                                                  | **Processing Spatial Data**                              | **Data Wrangling**                          | **Data Visualization**                          | **Sharing Data**                                  |
+---------------------------------------------------------------------+----------------------------------------------------------+---------------------------------------------+-------------------------------------------------+---------------------------------------------------+
| -   [`tidycensus`](https://walker-data.com/tidycensus/)             | -   [`sf`](https://r-spatial.github.io/sf/)              | -   [`dplyr`](https://dplyr.tidyverse.org/) | -   [`ggplot2`](https://ggplot2.tidyverse.org/) | -   [`rmarkdown`](https://rmarkdown.rstudio.com/) |
|                                                                     |                                                          |                                             |                                                 |                                                   |
| -   [`tigris`](https://github.com/walkerke/tigris)                  | -   [`terra`](https://rspatial.org/terra/pkg/index.html) | -   [`tidyr`](https://tidyr.tidyverse.org/) | -   [`tmap`](https://r-tmap.github.io/tmap/)    | -   [`shiny`](https://shiny.rstudio.com/)         |
|                                                                     |                                                          |                                             |                                                 |                                                   |
| -   [`rgbif`](https://docs.ropensci.org/rgbif/articles/rgbif.html)  |                                                          | -   [`readr`](https://readr.tidyverse.org/) |                                                 |                                                   |
+---------------------------------------------------------------------+----------------------------------------------------------+---------------------------------------------+-------------------------------------------------+---------------------------------------------------+
